# Generated by Django 4.0.4 on 2022-05-29 11:50

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal_Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('fathers_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('m', 'm'), ('f', 'f'), ('Other', 'Other')], max_length=5)),
                ('age', models.IntegerField()),
                ('crime', models.CharField(max_length=300)),
                ('crime_image', models.ImageField(upload_to=face.models.filepath)),
            ],
        ),
    ]
